### ISSUE TITLE
[IMPROVEMENT] 

### ISSUE THREAD

**Issue by kiranrega** [prakhartiwari0/Arito#67] opened 2023-01-23 12:42 UTC
## What improvement are you suggesting?

with out reloading the web page by click on that button we assign click event redirect to that starting page.

## Why should make this improvement?

user no need to got to reload. 
## How can we make these improvements?

simply by routing
## Additional Context

if it is  not suitable update please update me i am a beginner.

**Comment by prakhartiwari0** [comment] 2023-01-24 03:23
Can you explain what you want to do?

**Comment by singhimat99** [comment] 2023-02-01 00:01
Every time you refresh after interacting with something on the page, the browser shows a popup asking the user to confirm the refresh:
![Screen Shot 2023-01-31 at 3 54 51 PM](https://user-images.githubusercontent.com/105682846/215910673-136e1ae6-969c-496d-bcc1-ff6c6451a198.png)

I believe [kiranrega](https://github.com/kiranrega) is suggesting that the browser automatically refreshes without the popup.

I looked into this and noticed the default behavior of the window.onbeforeunload event was altered in the main.js file, so this may be an intended feature you might not want to change.

If the above is not the intended behaviour I would love to work on this issue.

**Comment by prakhartiwari0** [comment] 2023-02-01 06:19
Hey, @singhimat99 thanks for explaining the issue. Actually, I have put that code to ask before reloading to prevent users from losing progress, as I noticed a lot of times people click on the back button on mobile or close the tab on the desktop which erases their progress of the test if they did so while giving the test. 
Therefore, to prevent this from happening, I have temporarily created this ask message before reloading or exiting so that the progress is not lost accidentally.

But as I said this is a temporary feature, and it will be removed once we merge these two PRs soon: #53 and #72. The issue for addressing this problem is #33 & #70 respectively.

I hope I was able to explain, feel free to ask any questions.

Happy Contributing!

**Comment by prakhartiwari0** [comment] 2023-02-01 06:21
Also @kiranrega if you are also understanding this issue, then you may describe further if you want something else. Or if the issue is the same, you may close this one because it's not needed and similar issues are already open and people are working on them.

**Closed** 2023-02-19 15:35 UTC
Labels: enhancement
