### ISSUE TITLE
[IMPROVEMENT] 

### ISSUE THREAD

**Issue by Aryan123-rgb** [prakhartiwari0/Arito#144] opened 2023-05-23 11:09 UTC
## What improvement are you suggesting?
The get set go button on the home is not making the cursor turn pointer while hovering 

## Why should make this improvement?
It's a common practice to make any link on the page to set the property `cursor:pointer`

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

https://github.com/prakhartiwari0/Arito/assets/118872531/a446b443-252c-4bac-a16f-6c2a0173fbba

**Comment by Aryan123-rgb** [comment] 2023-05-24 02:18
If the issue is approved, it should be assigned to me as I am the one who has raised it :)

**Comment by gambhirsharma** [comment] 2023-07-03 06:08
This issue is a duplicate of #130 and this issue has already been assigned.

I am closing this issue.

**Closed by gambhirsharma** 2023-07-03 06:08 UTC
Labels: enhancement
